import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useEffect, useRef } from "react";
import dynamic from "next/dynamic";
const LightWeightChart = dynamic(
  () => import("../components/LineChart"),
  {
    ssr: false,
  }
);
const CandleStickChart = dynamic(
  () => import("../components/CandleStickChart"),
  {
    ssr: false,
  }
);
export const ChartComponent = (props) => {};
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.main}`}>
        <div className="w-2/3 h-auto">
          <LightWeightChart />
          <CandleStickChart />
        </div>
      </div>
    </div>
  );
}
